### ISSUE TITLE
can not  install component on OS-X

### ISSUE THREAD

**Issue by shnode** [pythoncn/june#86]
Well, when I run `make static`, it point out:
    
    (june)~/p/june git:master ❯ make static                                                                                     
    make[1]: component: No such file or directory
    make[1]: *** [components] Error 1
    make: *** [static] Error 2
    (june)~/p/june git:master ❯ 

So, I run `npm install -g component stylus uglify-js` as the README.rst said.

 `stylus` and `uglify-js` were successfully installed, but the `component` only left me a cursor rotating.

I have tried to use `$ npm install componentjs/component`, still only a cursor rotating on terminal.

And `npm ls` show me something like these:

    /Users/melodic/private/june
    └─┬component@1.0.1(git://github.com/componentjs/component#be27f93fd2fa8448023671afea2d14a286c2e0a4)
      ├── UNMET DEPENDENCY co@^3.0.0
      ├── UNMET DEPENDENCY commander@^2.2.0
      ├── UNMET DEPENDENCY component-build@^1.2.2
      ├── UNMET DEPENDENCY component-consoler@^2.0.0
      ├── UNMET DEPENDENCY component-flatten@^1.0.1
      ├── UNMET DEPENDENCY component-ls@^2.1.0
      ├── UNMET DEPENDENCY component-outdated2@^1.0.4
      ├── UNMET DEPENDENCY component-pin@^1.0.4
      ├── UNMET DEPENDENCY component-remotes@^1.1.6
      ├── UNMET DEPENDENCY component-resolver@^1.2.6
      ├── UNMET DEPENDENCY component-search2@^1.1.1
      ├── UNMET DEPENDENCY component-updater@^1.0.4
      ├── UNMET DEPENDENCY component-watcher@^1.0.1
      ├── UNMET DEPENDENCY debug@*
      ├── UNMET DEPENDENCY mkdirp@~0.3.5
      ├── UNMET DEPENDENCY rimraf@^2.2.6
      ├── UNMET DEPENDENCY semver@^2.2.1
      ├── UNMET DEPENDENCY superagent@~0.17.0
      ├── UNMET DEPENDENCY tiny-lr-fork@0.0.5
      └── UNMET DEPENDENCY win-fork@~1.1.1

    npm ERR! missing: component-build@^1.2.2, required by component@1.0.1
    npm ERR! missing: component-consoler@^2.0.0, required by component@1.0.1
    npm ERR! missing: component-flatten@^1.0.1, required by component@1.0.1
    npm ERR! missing: component-ls@^2.1.0, required by component@1.0.1
    npm ERR! missing: component-outdated2@^1.0.4, required by component@1.0.1
    npm ERR! missing: component-pin@^1.0.4, required by component@1.0.1
    npm ERR! missing: component-resolver@^1.2.6, required by component@1.0.1
    npm ERR! missing: component-search2@^1.1.1, required by component@1.0.1
    npm ERR! missing: component-updater@^1.0.4, required by component@1.0.1
    npm ERR! missing: component-watcher@^1.0.1, required by component@1.0.1
    npm ERR! missing: component-remotes@^1.1.6, required by component@1.0.1
    npm ERR! missing: commander@^2.2.0, required by component@1.0.1
    npm ERR! missing: semver@^2.2.1, required by component@1.0.1
    npm ERR! missing: mkdirp@~0.3.5, required by component@1.0.1
    npm ERR! missing: rimraf@^2.2.6, required by component@1.0.1
    npm ERR! missing: superagent@~0.17.0, required by component@1.0.1
    npm ERR! missing: win-fork@~1.1.1, required by component@1.0.1
    npm ERR! missing: debug@*, required by component@1.0.1
    npm ERR! missing: co@^3.0.0, required by component@1.0.1
    npm ERR! missing: tiny-lr-fork@0.0.5, required by component@1.0.1

What should I do to install this module?

**Comment by shnode** [comment]
Sorry, Done after a few minutes ago.

**Comment by chuck-bass** [comment]
I have the similar problem.How do you solve it?
